### ISSUE TITLE
Compressed route doesn't match original route

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/PACMAN#185]
Only shows up when mode = Debug in config script.

======================================================================
ERROR: test_run_light (p8_integration_tests.test_various.test_mwh_population_synfire.MwhPopulationSynfire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/p8_integration_tests/test_various/test_mwh_population_synfire.py", line 98, in test_run_light
    (v, gsyn, spikes) = do_run(nNeurons, neurons_per_core)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/p8_integration_tests/test_various/test_mwh_population_synfire.py", line 64, in do_run
    p.run(1500)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/__init__.py", line 618, in run
    return __pynn["run"](simtime, callbacks=callbacks)
  File "/localhome/mbbssag3/Downloads/PyNN/PyNN-0.9.1/PyNN9/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/localhome/mbbssag3/Downloads/PyNN/PyNN-0.9.1/PyNN9/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/spinnaker.py", line 123, in run_until
    self._run_wait(tstop - self.t)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker8/spynnaker8/spinnaker.py", line 166, in _run_wait
    super(SpiNNaker, self).run(duration_ms)
  File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 317, in run
    super(AbstractSpiNNakerCommon, self).run(run_time)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 835, in run
    self._run(run_time)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1015, in _run
    self._do_load(application_graph_changed)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1873, in _do_load
    optional_algorithms)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1226, in _run_algorithms
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1211, in _run_algorithms
    executor.execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 626, in execute_mapping
    self._execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 642, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 46, in call
    results = self.call_python(method_inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/python_function_algorithm.py", line 45, in call_python
    return function(**inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 151, in generate_routing_compression_checker_report
    compare_route(f, o_route, compressed_dict)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 111, in compare_route
    compare_route(f, o_route, compressed_dict, o_code=o_code, start=i+1)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 111, in compare_route
    compare_route(f, o_route, compressed_dict, o_code=o_code, start=i+1)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 111, in compare_route
    compare_route(f, o_route, compressed_dict, o_code=o_code, start=i+1)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 111, in compare_route
    compare_route(f, o_route, compressed_dict, o_code=o_code, start=i+1)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 111, in compare_route
    compare_route(f, o_route, compressed_dict, o_code=o_code, start=i+1)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/operations/algorithm_reports/routing_compression_checker_report.py", line 97, in compare_route
    "a different defaultable value.".format(c_route, o_route))
pacman.exceptions.PacmanRoutingException: Compressed route 15168:4294967232:False:{}:{0} covers original route 15168:4294967232:True:{}:{0} but has a different defaultable value.

**Comment by alan-stokes** [comment]
well thats very worrying. the router checker is meant to verify that the compressed routes behave as the original routes would have. but there is a known difference that i persumed the router checker checks as well, which is that the compressor can cover more key space than declaired, if theres not expected keys to go through the router. 

it might not be bad to switch from defaultable to not...... but it woudl need a lot of investigating to verify.

**Comment by rowleya** [comment]
Pretty sure there is no issue with something becoming non-defaultable after compression.  This might mean that the route was merged with another one for example.  Compression will probably remove all default routes in general.

**Comment by andrewgait** [comment]
I think a lot of the conversation around this has moved on and we’re well aware of the issues involved in routing and compression.  Also, the test which caught this issue originally didn’t make the cut when the integration tests were updated, so for both those reasons I’m going to close this issue.
